server:
  port: 0  # Let Spring Boot assign a random port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Default Eureka Server

spring:
  cloud:
    config:
      allow-override: true
      override-none: false
      override-system-properties: false
