spring:
  application:
    name: ASA  # Service name must match

  data:
    mongodb:
      uri: mongodb://localhost:27017/csc  # Default MongoDB connection

server:
  port: 8082  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
